apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend1-container
        image: nginx
        ports:
        - containerPort: 80